from django.urls import path
from .views import *

urlpatterns = [
    path('', list, name="home"),
    path('list_restaurant/', list_restaurant, name="list_restaurant"),
    path('list_food/', list_food, name="list_food"),
    path('best_restaurant/', best_restaurant, name="best_restaurant"),
    path('best_food/', best_food, name="best_food"),
    # path('profile_manager/', profile_manager, name="profile_manager"),
    path('search/', search, name='search'),
    path('search2/', search2, name='search2'),
    path('restaurant/', RestaurantList.as_view(), name='restaurant'),
    path('restaurant/<int:pk>', RestaurantDetail.as_view()),
    path('branch/', BranchList.as_view(), name='branch'),
    path('branch/<int:pk>', BranchDetail.as_view()),
    path('food/', FoodList.as_view(), name='food'),
    path('food/<int:pk>', FoodDetail.as_view()),
    path('categorymeel/', CategoryMeelList.as_view(), name='categorymeel'),
    path('categorymeel/<int:pk>', CategoryMeelDetail.as_view()),
    path('categoryfood/', CategoryFoodList.as_view(), name='categoryfood'),
    path('categoryfood/<int:pk>', CategoryFoodDetail.as_view()),
    path('menu/', MenuList.as_view(), name='menu'),
    path('menu/<int:pk>', MenuDetail.as_view()),
    path('orderitem/', OrderItemList.as_view(), name='orderitem'),
    path('orderitem/<int:pk>', OrderItemDetail.as_view()),
    path('order/', OrderList.as_view(), name='order'),
    path('order/<int:pk>', OrderDetail.as_view()),
    path('seareh2/', search21, name='seareh2'),
    path('rest_create/', rest_create, name='rest_create'),
    path('category1_create/', category1_create, name='category1_create'),
    path('category2_create/', category2_create, name='category2_create'),
    path('branch_create/', branch_create, name='branch_create'),
    path('menu_create/', menu_create, name='menu_create'),
    path('food_create/', food_create, name='food_create'),
    path('edit/<int:pk>/', rest_edit, name='edit'),
    path('del/<int:pk>/', rest_del, name='del'),
    path('sss/', list_view, name='views'),
    path('orders/', orders, name='orders')
]
