# Generated by Django 3.2.9 on 2021-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('main_address', models.TextField(max_length=300)),
                ('postal_code', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('national_code', models.CharField(max_length=10)),
                ('birthday_time', models.DateTimeField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'famale')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.ManyToManyField(to='account.Address')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('national_code', models.CharField(max_length=10)),
                ('birthday_time', models.DateTimeField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'famale')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.ManyToManyField(to='account.Address')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
    ]
