# Generated by Django 3.2.2 on 2022-01-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ManyToManyField(to='account.Customer'),
        ),
    ]
