# Generated by Django 3.2.2 on 2022-01-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, related_name='x', to='account.Customer'),
        ),
    ]
