# Generated by Django 3.2.2 on 2022-01-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_id',
            field=models.ManyToManyField(related_name='orderitem_set', to='store.Menu'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='category_food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_set1', to='store.categoryfood'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_set', to='store.restaurant'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category_food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_set', to='store.categoryfood'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_sett', to='store.branch'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_set', to='store.food'),
        ),
    ]
