# Generated by Django 4.0.1 on 2022-02-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_address_address_address_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('N', 'new'), ('M', 'main')], default='M', max_length=1),
        ),
    ]
