# Generated by Django 4.0.1 on 2022-02-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_address2_alter_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
