# Generated by Django 4.0.1 on 2022-02-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
    ]
